#!/bin/bash

if nc -z localhost 2522; then
    if nc -z localhost 2523; then
        echo "Cloakserver and groupserver are running"
        exit 0
    else
        echo "Groupserver is not running on port 2523"
        exit 1
    fi
else
    echo "Cloakserver is not running on port 2522"
    exit 2
fi
