#!/bin/bash

PID=$(ps ax | grep 'mumble-auth' | grep -v grep | awk '{print $1}')
if [ $PID ]; then
	echo "mumble-auth is running with PID" $PID;
	exit 0
else
	echo "Can't find mumble-auth process (mumble-djangoauth.py).";
	exit 2
fi

