#!/bin/sh

# Credits go to: http://lzone.de/blog/Nagios%20Plugin%20for%20dmesg%20Monitoring

SEVERITIES="err,alert,emerg,crit"
WHITELIST="\
microcode: |\
Firmware Bug|\
i8042: No controller|\
Odd, counter constraints enabled but no core perfctrs detected|\
Failed to access perfctr msr|\
echo 0 > /proc/sys|\
radeon 0000:0b:05.0|\
drm:r100_cp_init|\
Assuming drive cache: write through|\
piix4_smbus 0000:00:07.3|\
intel_rapl:|\
Ignoring unsafe software power cap!|\
watchdog: iTCO_wdt: cannot register|\
watchdog: iTCO_wdt: a legacy watchdog module is probably present.|\
kvm: disabled by bios|\
radeon kernel modesetting for R600 or later requires firmware-linux-nonfree."

output=$(sudo dmesg -T -l "$SEVERITIES" | egrep -v "$WHITELIST")

if [ -z "$output" ]; then
    echo "All is fine."
    exit 0
else
    echo "Warning: There are errors in the kernel log!"
    echo "$output"
    exit 1
fi
