#!/bin/sh
FAILED=$(systemctl --failed --no-legend --plain | cut -d ' ' -f 1)

if [ "$FAILED" ]; then
	echo "Failed systemd services:"
    for SERVICE in $FAILED; do
        echo $SERVICE
    done
	exit 2
else
	echo "No systemd failures."
	exit 0
fi
