#!/bin/sh

# XXX: add the following sudo access rights to /etc/sudoers.d/zfs:
# Cmnd_Alias C_ZFS = \
# /sbin/zfs "", /sbin/zfs help *, \
# /sbin/zfs get, /sbin/zfs get *, \
# /sbin/zfs list, /sbin/zfs list *, \
# /sbin/zpool "", /sbin/zpool help *, \
# /sbin/zpool iostat, /sbin/zpool iostat *, \
# /sbin/zpool list, /sbin/zpool list *, \
# /sbin/zpool status, /sbin/zpool status *
# nagios ALL = (R_ROOT) NOPASSWD: C_ZFS

if sudo zpool list -Ho health | grep -v ONLINE > /dev/null; then
    echo "ZFS: At least one pool's health is not ONLINE!"
    sudo zpool status -x
    exit 2
fi

sudo zpool list -Ho capacity | cut -d% -f 1 | while read capacity; do
    if [ "$capacity" -gt 80 ]; then
        echo "ZFS: At least one pool is nearly full!"
        sudo zpool list -o name,capacity,free
        exit 1
    fi
done

echo "ZFS: Everything is fine."
exit 0
