#!/bin/sh

if sudo zpool list -Ho health | grep -v ONLINE > /dev/null; then
    echo "ZFS: At least one pool's health is not ONLINE!"
    sudo zpool status -x
    exit 2
fi

for capacity in "$(sudo zpool list -Ho capacity | cut -d% -f 1)"; do
    if [ "$capacity" -gt 80 ]; then
        echo "ZFS: At least one pool is nearly full!"
        sudo zpool list -o name,capacity,free
        exit 1
    fi
done

echo "ZFS: Everything is fine."
exit 0
